# Generated by Django 4.0.5 on 2022-09-22 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grouped_room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=255)),
                ('price_pernight', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='room/room_image')),
                ('status', models.CharField(choices=[('available', 'available'), ('booked', 'booked'), ('not-confirm', 'confirm'), ('cancled', 'cancled'), ('cleaning', 'cleaning'), ('maintainance', 'maintainance')], default='available', max_length=255)),
                ('group', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='roomapp.grouped_room')),
            ],
        ),
    ]
