# Generated by Django 4.0.5 on 2022-09-22 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='image',
        ),
    ]
