# Generated by Django 4.0.5 on 2022-09-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomapp', '0002_remove_room_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='final_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='intital_number',
            field=models.IntegerField(default=0),
        ),
    ]
