# Generated by Django 4.0.5 on 2022-09-22 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roomapp', '0003_room_final_number_room_intital_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('user', models.CharField(default='#LPH1ZI', max_length=255, unique=True)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('designation', models.CharField(blank=True, max_length=255)),
                ('passport_id_number', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.IntegerField(blank=True, help_text='Contact phone number')),
                ('nationality', models.CharField(blank=True, max_length=155)),
                ('tel_fax', models.CharField(blank=True, max_length=255)),
                ('traval_agent', models.CharField(blank=True, max_length=255)),
                ('bill_setteled_by', models.CharField(blank=True, max_length=255)),
                ('booked_by', models.CharField(blank=True, max_length=255)),
                ('check_in', models.DateTimeField(null=True)),
                ('check_out', models.DateTimeField(null=True)),
                ('main_id', models.ImageField(null=True, upload_to='customer/id')),
            ],
        ),
        migrations.CreateModel(
            name='Booked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('child', models.IntegerField(default=0, null=True)),
                ('male_number', models.IntegerField(default=0, null=True)),
                ('female_number', models.IntegerField(default=0, null=True)),
                ('other_gender', models.IntegerField(default=0, null=True)),
                ('status', models.BooleanField(default=False)),
                ('customer_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='roomapp.customer')),
                ('room_id', models.ManyToManyField(blank=True, to='roomapp.room')),
            ],
            options={
                'ordering': ['-booked_date'],
            },
        ),
    ]
