# Generated by Django 4.0.5 on 2022-09-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomapp', '0004_customer_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='booked',
            name='number_of_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.CharField(default='#PCNCFS', max_length=255, unique=True),
        ),
    ]
