# Generated by Django 4.0.5 on 2022-09-23 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roomapp', '0008_alter_customer_user_customer_list_ch_out_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.CharField(default='#SLC228', max_length=255),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default='#M1SGPF', max_length=255, unique=True)),
                ('total', models.CharField(blank=True, max_length=255, null=True)),
                ('order_status', models.CharField(choices=[('NEW', 'NEW'), ('APPROVED', 'APPROVED'), ('CANCLE', 'CANCLE'), ('DISPATCHED', 'DISPATCHED'), ('RECIVED', 'RECIVED'), ('Delivered', 'Delivered')], default='NEW', max_length=255, null=True)),
                ('payment_type', models.CharField(choices=[('PAID', 'PAID'), ('UNPAID', 'UNPAID')], default='UNPAID', max_length=255, null=True)),
                ('order_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roomapp.customer')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roomapp.room')),
            ],
        ),
    ]
