# Generated by Django 4.0.5 on 2022-09-23 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roomapp', '0009_alter_customer_user_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.CharField(default='#GC00S4', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='#OEITC9', max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='Additional_id',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_id', models.ImageField(blank=True, null=True, upload_to='customer/add_id')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='roomapp.customer')),
            ],
        ),
    ]
