# Generated by Django 4.0.5 on 2022-09-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomapp', '0010_alter_customer_user_alter_order_order_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Non_room_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default='#H3N41R', max_length=255, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('total', models.FloatField(blank=True, max_length=255, null=True)),
                ('payment_type', models.CharField(choices=[('PAID', 'PAID'), ('UNPAID', 'UNPAID')], default='UNPAID', max_length=255, null=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.CharField(default='#0KNREF', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='#GZ9MLE', max_length=255, unique=True),
        ),
    ]
