# Generated by Django 4.0.5 on 2022-09-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomapp', '0011_non_room_user_alter_customer_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_type',
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.CharField(default='#2QDNPJ', max_length=255),
        ),
        migrations.AlterField(
            model_name='non_room_user',
            name='order_id',
            field=models.CharField(default='#UM14U8', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='#TMAWFB', max_length=255, unique=True),
        ),
    ]
