# Generated by Django 4.0.5 on 2022-09-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomapp', '0012_remove_order_order_status_remove_order_payment_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='non_room_user',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='non_room_user',
            name='amount_paid',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='non_room_user',
            name='remaing_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.CharField(default='#AN7YXV', max_length=255),
        ),
        migrations.AlterField(
            model_name='non_room_user',
            name='order_id',
            field=models.CharField(default='#2P9TKU', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='#LG3UMM', max_length=255, unique=True),
        ),
    ]
