# Generated by Django 4.0.5 on 2022-09-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomapp', '0013_remove_non_room_user_payment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='non_room_user',
            name='Payment_mode',
            field=models.CharField(choices=[('Esewa', 'Eswa'), ('Khalti', 'Khalti'), ('Bank Transfer', 'Bank Transfer'), ('Cash', 'Cash'), ('Other', 'Other')], default='UNPAID', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.CharField(default='#V9V3CD', max_length=255),
        ),
        migrations.AlterField(
            model_name='non_room_user',
            name='order_id',
            field=models.CharField(default='#6EMP0W', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='#MHGTXB', max_length=255, unique=True),
        ),
    ]
