# Generated by Django 4.0.5 on 2022-09-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomapp', '0014_non_room_user_payment_mode_alter_customer_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.CharField(default='#4F11BM', max_length=255),
        ),
        migrations.AlterField(
            model_name='non_room_user',
            name='order_id',
            field=models.CharField(default='#SL11YY', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='#833HZD', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('booked', 'booked'), ('not-confirm', 'confirm'), ('cancled', 'cancled'), ('cleaning', 'cleaning'), ('maintenance', 'maintenance')], default='available', max_length=255),
        ),
    ]
