# Generated by Django 4.0.5 on 2022-09-26 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomapp', '0018_alter_customer_phone_number_alter_customer_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booked',
            name='child',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='booked',
            name='female_number',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='booked',
            name='male_number',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='booked',
            name='other_gender',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.CharField(default='#66Q5BO', max_length=255),
        ),
        migrations.AlterField(
            model_name='non_room_user',
            name='order_id',
            field=models.CharField(default='#KYC6FG', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='#I24ABM', max_length=255, unique=True),
        ),
    ]
