# Generated by Django 4.0.5 on 2022-09-26 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomapp', '0020_alter_booked_child_alter_booked_female_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.CharField(default='#UKCNNB', max_length=255),
        ),
        migrations.AlterField(
            model_name='non_room_user',
            name='order_id',
            field=models.CharField(default='#HRKESE', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='#TAS3IM', max_length=255, unique=True),
        ),
    ]
