# Generated by Django 4.0.5 on 2022-09-26 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomapp', '0021_alter_customer_user_alter_non_room_user_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booked',
            name='number_of_days',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.CharField(default='#4H24U4', max_length=255),
        ),
        migrations.AlterField(
            model_name='non_room_user',
            name='order_id',
            field=models.CharField(default='#6IY0JG', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='#4RRHQ1', max_length=255, unique=True),
        ),
    ]
