# Generated by Django 4.0.5 on 2022-10-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomapp', '0025_alter_customer_user_alter_non_room_user_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='tel_fax',
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.CharField(default='#SKQVG1', max_length=255),
        ),
        migrations.AlterField(
            model_name='non_room_user',
            name='order_id',
            field=models.CharField(default='#51001N', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='#NC4LR2', max_length=255, unique=True),
        ),
    ]
