# Generated by Django 4.0.5 on 2022-10-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomapp', '0026_remove_customer_tel_fax_alter_customer_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_list',
            name='checkin',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='booked_by',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='main_id',
            field=models.ImageField(null=True, upload_to='customer/id'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.CharField(default='#I6VYCU', max_length=255),
        ),
        migrations.AlterField(
            model_name='non_room_user',
            name='order_id',
            field=models.CharField(default='#XFYH9V', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='#FIARY9', max_length=255, unique=True),
        ),
    ]
