# Generated by Django 4.0.5 on 2022-10-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomapp', '0027_customer_list_checkin_alter_customer_booked_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='final_number',
        ),
        migrations.RemoveField(
            model_name='room',
            name='intital_number',
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.CharField(default='#3275WZ', max_length=255),
        ),
        migrations.AlterField(
            model_name='non_room_user',
            name='order_id',
            field=models.CharField(default='#4IDRWV', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='#XBMBDM', max_length=255, unique=True),
        ),
    ]
