# Generated by Django 4.0.5 on 2022-11-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomapp', '0029_customer_remarks_alter_customer_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='main_id',
            field=models.ImageField(blank=True, null=True, upload_to='customer/id'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.CharField(default='#WJU4T8', max_length=255),
        ),
        migrations.AlterField(
            model_name='non_room_user',
            name='order_id',
            field=models.CharField(default='#JVD0DA', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='#OUH3UD', max_length=255, unique=True),
        ),
    ]
